app/blog/routes.py
from flask import Blueprint,render_template,request,redirect,url_for
from flask_login import current_user, login_required
from sqlalchemy import asc, desc



from .forms import CreatePostForm, postComment
from app.models import Post, postComments, User

blog = Blueprint('blog',__name__,template_folder='blog_templates')

from app.models import db


@blog.route('/blog/main')
@login_required
def blogHome():
    posts = Post.query.order_by(desc(Post.date_created)).all()
    return render_template('blog.html' ,posts = posts,current=current_user.id)

@blog.route('/posts/create', methods=["GET","POST"])
@login_required
def createPost():
    user= current_user
    form = CreatePostForm()
    if request.method == "POST":
            if form.validate():
                print('form was validated')
                title = form.title.data
                image = form.image.data
                content = form.content.data

                # create instance of post
                post = Post(title, image, content, current_user.id)
                # add instance of database 
                db.session.add(post)
                # commit to database like github
                db.session.commit()
            
                return redirect(url_for('blog.blogHome'))

    return render_template('createpost.html', form=form, user=user)

@blog.route('/posts/<int:id>', methods=['GET','POST'])
@login_required
def singlePostPage(id):
    post = Post.query.filter_by(id=id).first()
    comment = postComment()
    comments=postComments.query.order_by(desc(postComments.date_added)).all()
    users=db.session.query(User).join(postComments)
    if request.method == 'POST':
        if comment.validate_on_submit:
            com = comment.comment.data
            comnt=postComments(com,current_user.id,id)
            db.session.add(comnt)
            db.session.commit()

            return redirect(url_for('blog.singlePostPage', id=id))

    return render_template('post_page.html',p=post,users=users,comment=comment,current=current_user.id,comments=comments,id=id, title='Post Page')

@blog.route('/posts/delete/<int:id>', methods=['GET','POST'])
@login_required
def deleteComment(id):
    comment=postComments.query.filter_by(id=id).first()
    pageid=comment.postId
    if request.method == 'POST':
        
        db.session.delete(comment)
        db.session.commit()
    
    return redirect(url_for('blog.singlePostPage', id=pageid))

@blog.route('/posts/postlike/<int:id>', methods=['GET','POST'])
@login_required
def postLikeIt(id):
    post=Post.query.filter_by(id=id).first()
    if request.method=='POST':
        post.like=True
        db.session.commit()

    return redirect(url_for('blog.singlePostPage', id=id))

@blog.route('/posts/commentlike/<int:id>', methods=['GET','POST'])
@login_required
def commentLikeIt(id):
    comment=postComments.query.filter_by(id=id).first()
    pageid=comment.postId
    if request.method=='POST':
        comment.like=True
        db.session.commit()

    return redirect(url_for('blog.singlePostPage', id=pageid))

@blog.route('/posts/postdislike/<int:id>', methods=['GET','POST'])
@login_required
def postDislikeIt(id):
    post=Post.query.filter_by(id=id).first()
    if request.method=='POST':
        post.dislike=True
        db.session.commit()

    return redirect(url_for('blog.singlePostPage', id=id))

@blog.route('/posts/commentdislike/<int:id>', methods=['GET','POST'])
@login_required
def commentDislikeIt(id):
    comment=postComments.query.filter_by(id=id).first()
    pageid=comment.postId
    if request.method=='POST':
        comment.dislike=True
        db.session.commit()

    return redirect(url_for('blog.singlePostPage', id=pageid))

@blog.route('/posts/homepostlike/<int:id>', methods=['GET','POST'])
@login_required
def homePostLikeIt(id):
    post=Post.query.filter_by(id=id).first()
    if request.method=='POST':
        post.like=True
        db.session.commit()

    return redirect(url_for('blog.blogHome'))

@blog.route('/posts/homepostdislike/<int:id>', methods=['GET','POST'])
@login_required
def homePostDislikeIt(id):
    post=Post.query.filter_by(id=id).first()
    if request.method=='POST':
        post.dislike=True
        db.session.commit()

    return redirect(url_for('blog.blogHome'))

@blog.route('/posts/unlike/<int:id>',methods=['GET','POST'])
@login_required
def homePostUnlike(id):
    post=Post.query.filter_by(id=id).first()
    if request.method=='POST':
        post.like=False
        db.session.commit()
    return redirect(url_for('blog.blogHome'))

@blog.route('/posts/postsunlike/<int:id>',methods=['GET','POST'])
@login_required
def postUnlike(id):
    post=Post.query.filter_by(id=id).first()
    if request.method=='POST':
        post.like=False
        db.session.commit()
    return redirect(url_for('blog.singlePostPage',id=id))

@blog.route('/posts/commentsunlike/<int:id>',methods=['GET','POST'])
@login_required
def commentUnlike(id):
    comment=postComments.query.filter_by(id=id).first()
    pageid=comment.postId
    if request.method=='POST':
        comment.like=False
        db.session.commit()
    return redirect(url_for('blog.singlePostPage',id=pageid))

@blog.route('/posts/undislike/<int:id>',methods=['GET','POST'])
@login_required
def homePostUndislike(id):
    post=Post.query.filter_by(id=id).first()
    if request.method=='POST':
        post.dislike=False
        db.session.commit()
    return redirect(url_for('blog.blogHome'))

@blog.route('/posts/postsundislike/<int:id>',methods=['GET','POST'])
@login_required
def postUndislike(id):
    post=Post.query.filter_by(id=id).first()
    if request.method=='POST':
        post.dislike=False
        db.session.commit()
    return redirect(url_for('blog.singlePostPage', id=id))

@blog.route('/posts/commentsundislike/<int:id>',methods=['GET','POST'])
@login_required
def commentUndislike(id):
    comment=postComments.query.filter_by(id=id).first()
    pageid=comment.postId
    if request.method=='POST':
        comment.dislike=False
        db.session.commit()
    return redirect(url_for('blog.singlePostPage', id=pageid))

app/templates/about.html
{% extends 'base.html' %}

{% block content %}
<h1 align="center">This is Uh... Social Media</h1>
<h3>Create an account and share your favorite pics! </h3>
{% endblock content %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
<title>{{title}}</title>
</head>
<body>
    {% include 'nav.html' %}
    <main class="container">
        {% block content %}

        {% endblock content %}
    </main>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>

app/templates/index.html
{% extends 'base.html' %}

{% block content %}

<h1 align="center">Welcome to Our Really Generic Social media page</h1>
<h2 align="center"> please log in to view and make posts</h2>
{% endblock content %}

app/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Social Uh... Media</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a
            class="nav-link active"
            aria-current="page"
            href="{{ url_for('blog.blogHome') }}"
            >Home</a
          >
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('about')}}">About</a>
        </li
        {% if current_user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('blog.createPost') }}"
          >Create Post</a
          >
        </li>
        <li class="nav-item">
          <p class="nav-link" href="#">Hello, {{ current_user.username }}</p>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('auth.logMeOut') }}">Log Out</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a
          class="nav-link active"
          aria-current="page"
          href="{{ url_for('auth.logMeIn') }}"
          >Log In</a
          >
        </li>
        <li class="nav-item">
          <a
          class="nav-link active"
          aria-current="page"
          href="{{ url_for('auth.signUp') }}"
            >Sign Up</a
          >
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>